### ISSUE TITLE
error 400 and 404

### ISSUE THREAD

**Issue by affer** [d-Rickyy-b/node-red-contrib-ffpass#7] opened 2022-06-24 18:17 UTC
<img width="1491" alt="Screenshot 2022-06-24 at 20 15 17" src="https://user-images.githubusercontent.com/3717164/175619572-0c11c207-ca4d-41fd-b50f-6fa08782fdb7.png">

Getting these errors suddenly.. Auth checked in other app on same ip.. working. do you (developer) experience same problems?  not sure if i can find some sort of log?

**Comment by affer** [comment] 2022-06-26 20:11
could it be the same issue as here? https://github.com/itchannel/fordpass-ha/issues/180

**Comment by d-Rickyy-b** [comment] 2022-06-28 18:12
Hi there and sorry for the long wait. I created this module for a friend of mine, so I can't exactly tell you if this module is faulty. Are you on the latest version of the node-red-contrib-ffpass module? I just updated the version in the node-red store to 0.1.6. Connection issues were fixed with 0.1.5 already, so I am wondering what the issue might be for you.

**Comment by d-Rickyy-b** [comment] 2022-06-28 18:17
Oh I just checked - you don't only have 400 and 404 errors, you also got 401 errors as well which indicate that you are not authenticated (as can be seen at the ffpass start method -> "Auth failed"). Please check that your username/password is correct. I assume there's an issue with your login credentials.

**Comment by affer** [comment] 2022-06-28 18:27
No worries.. i have the 401 also yes.. ive tested in a new node red instance, and tried new entering of my login, pass and vin.. same result. 

my login credential is working in other app on same ip and of-cause in fordpass app. see my link above to another faulty login behaviour with authentication.. my challenge came around at the same time, is it working for you [d-Rickyy-b](https://github.com/d-Rickyy-b)?

**Comment by affer** [comment] 2022-07-03 21:01
and yes, it is with both 0.15 and 0.16, is it working for your friend =?

**Comment by affer** [comment] 2022-07-05 07:05
i can see on this app that login for ford api also have had some issues.. but solved now. https://github.com/tonesto7/fordpass-scriptable/issues/111

**Comment by affer** [comment] 2022-07-05 19:10
above link is with inspiration from here: https://github.com/itchannel/fordpass-ha/issues/187

**Comment by d-Rickyy-b** [comment] 2022-07-05 22:03
If what you are saying is true, we need to create this issue on https://github.com/d4v3y0rk/ffpass-module, because this project is just a wrapper around the ffpass-module. I'll definitely come back to you, @affer. But for now I won't have time until after the next two weeks.

Thank you for your time reporting the issue. If there hasn't been a fix for it two weeks from now, I'll try to get inspiration from the projects you linked.

**Comment by sebamelo-fr** [comment] 2022-08-23 20:25
Hi d-Rickyy-b
Any progress on this issue?
Thank you

**Comment by d-Rickyy-b** [comment] 2022-08-23 22:42
Hi @affer, hi @sebamelo-fr,

seems like there's a fix in this python project ready to be implemented: https://github.com/ianjwhite99/connected-car-python-sdk/commit/e4a23f9de98d5e78a4a7f4ccf656c7061b01d572

Still the issue is not with this project, but rather of the underlying ffpass-module: https://github.com/d4v3y0rk/ffpass-module/issues/20

I'll have a look asap - probably by the end of the week.

**Comment by affer** [comment] 2022-09-17 16:48
Hi Rickyy

any luck ? (hopes attached)

**Comment by d-Rickyy-b** [comment] 2022-09-20 01:21
Hi @affer,

I'm [working on it](https://github.com/d-Rickyy-b/ffpass-module/tree/fix-auth).

**Closed as completed** 2022-10-05 14:45 UTC
